name: Run Selenium Project

on:
  push:
    branches:
      - main  # Run on push to the main branch

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Chrome
        uses: juliangruber/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium script
        run: python z.py